server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://node1:3306/cloud_goods?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: node1:9200
      cluster-name: elasticsearch
      repositories:
        enabled: true
  redis:
    host: node1